import type { Metadata } from "next";
import { Reenie_Beanie, VT323 } from "next/font/google";
import "./globals.css";
import { Providers } from "./components/providers";

const reenieBeanie = Reenie_Beanie({
  weight: "400",
  variable: "--font-reenie-beanie",
  subsets: ["latin"],
});

const vt323 = VT323({
  weight: "400",
  variable: "--font-vt323",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${reenieBeanie.variable} ${vt323.variable} antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
